### ISSUE TITLE
opening single file gives error

### ISSUE THREAD

**Issue by codeHorse87** [abaplint/vscode-abaplint#101]
Hi, 
I've just installed larshp.vscode-abap v0.5.4 and larshp.vscode-abaplint v.0.4.183 on vscode with:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (2 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

when opening any kind of ABAP file I get the following output from the Language Server ABAP:
>Folder overview:
no custom abaplint config, using defaults
(node:12147) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'root' of undefined
    at Handler.<anonymous> (/Users/user/.vscode/extensions/larshp.vscode-abaplint-0.4.183/server/out/server.js:9562:54)
    at Generator.next (<anonymous>)
    at /Users/user/.vscode/extensions/larshp.vscode-abaplint-0.4.183/server/out/server.js:9422:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/.vscode/extensions/larshp.vscode-abaplint-0.4.183/server/out/server.js:9418:12)
    at Handler.addDependencies (/Users/user/.vscode/extensions/larshp.vscode-abaplint-0.4.183/server/out/server.js:9555:16)
    at Handler.<anonymous> (/Users/user/.vscode/extensions/larshp.vscode-abaplint-0.4.183/server/out/server.js:9549:24)
    at Generator.next (<anonymous>)
    at /Users/user/.vscode/extensions/larshp.vscode-abaplint-0.4.183/server/out/server.js:9422:71
    at new Promise (<anonymous>)
(node:12147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

By a quick glimpse to the code it seems that some default configuration is not loaded as an argument. Do I miss something at all to make linting work? 

Hope this helps to improve the good work!

**Comment by larshp** [comment]
hi,
opening just a single file might not work, also using multi root workspaces might have problems

try opening a folder via "File" -> "Open Folder..." to see if it gives the same error

**Comment by codeHorse87** [comment]
thanks @larshp opening a folder made it work

**Comment by larshp** [comment]
cool, lets keep the issue open, I'll change the title

**Comment by larshp** [comment]
@codeHorse87 try again, larshp.vscode-abaplint@0.4.223 published, might be a few minutes before the marketplace updates

**Comment by codeHorse87** [comment]
works. linter is not breaking anymore
