### ISSUE TITLE
'file not found' error when opening abaplint for any ABAP file

### ISSUE THREAD

**Issue by g0ldfinch** [abaplint/vscode-abaplint#109]
I tried **abaplint** in the most recent VSCode (1.53.2). When I open any .abap file on my computer, and then click the **abaplint** button, I get this error:
![image](https://user-images.githubusercontent.com/22842680/109233672-6132c000-781e-11eb-974f-3c38f1d0dd3d.png)
Obviously, that can't be right because I'm editing an EXISTING file. Copying the latter to a different location doesn't help either. I'm using a default configuration.
Another variation of the error is _**output:extension-output-%239 (1, 1)file not found**_.
When I restarted VSCode and tried the same, **abaplint** started showing **_loading_** indefinitely, and this error popped-up:

> Running the contributed command: 'abaplint.show' failed.

![image](https://user-images.githubusercontent.com/22842680/109234296-8673fe00-781f-11eb-8402-7bc8e39ee72c.png)

Obviously, navigation to definitions or syntax check aren't working. Clearly, something's wrong with the extension in my case. I'm not proficient in VSCode. What else should I provide to help with the error?

**Comment by larshp** [comment]
see https://github.com/abaplint/vscode-abaplint/issues/101, opening a single file doesnt really work, try opening a folder

eg clone https://github.com/abapGit/abapGit into a folder, and open that folder

**Comment by g0ldfinch** [comment]
Is there a difference between opening a folder and a file? Besides, I opened a repository, which should be kind of the same as opening a folder. Anyways, it didn't work:
![image](https://user-images.githubusercontent.com/22842680/109272316-d1643480-7864-11eb-83b3-a96c4d438b50.png)

BTW, does **abaplint** work only with repos created via **abapGIT**, or can I have my own text files with the ABAP code, and lint will be able to parse them?

**Comment by larshp** [comment]
the vscode api works different for folders and files and workspaces

you need to at least follow the same file naming as abapGit, ie a PROG object should be `<name>.prog.abap`

**Comment by g0ldfinch** [comment]
I see... So, no chances for me to use it then. I already have repos that don't follow that file naming convention. And there is no way to install abapGIT in our R/3 4.7...
I'll test this with the naming conventions as you suggested and will let you know if this works. Is there a documentation how different objects' files must be named? As I said, I can't install abapGIT in kernel 620, so have to rely on the documentation to name files properly.

**Comment by larshp** [comment]
just rename the files in the repo?

https://github.com/abapGit-tests contains examples with many different object types, for PROG + CLAS objects, the XML files are not required, but for FUGR I think abaplint will need the XML files

**Comment by larshp** [comment]
abapGit will only work on 702 and up, its difficult to make it work below that

**Comment by g0ldfinch** [comment]
I know, I tried (: Too many kernel things must be backported - working full time on BAU/projects doesn't leave any time for that.

**Comment by g0ldfinch** [comment]
and it still isn't clear why abaplint reports that it can't find a file...

**Comment by larshp** [comment]
abaplint ignores all files that does not follow the abapGit naming scheme, eg PROG should be `<name>.prog.abap`

**Comment by larshp** [comment]
@g0ldfinch did above help?

**Comment by larshp** [comment]
closing, no reply
