### ISSUE TITLE
Request textDocument/formatting failed. 

### ISSUE THREAD

**Issue by codegobbo** [abaplint/vscode-abaplint#110]
I can't get the abaplint extension to run.
I get the below error.

[Error - 13:31:17] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'root' of undefined
  Code: -32603 

Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Name: abaplint
Id: larshp.vscode-abaplint
Description: ABAP linting, problems view, go to definition, find references, and quick fixes.
Version: 0.4.222
Publisher: Lars Hvam
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint

**Comment by larshp** [comment]
@codegobbo try again, larshp.vscode-abaplint@0.4.223 published, might be a few minutes before the marketplace updates

**Comment by codegobbo** [comment]
I have updated to 0.4.223 and i have tried to open a folder.
Now i get this:

(node:12780) UnhandledPromiseRejectionWarning: Error: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
    at checkExecSyncError (child_process.js:639:11)
    at Object.execSync (child_process.js:675:15)
    at Object.execSync (electron/js2c/asar_bundle.js:5:12113)
    at Function.<anonymous> (c:\Users\haegelet\.vscode\extensions\larshp.vscode-abaplint-0.4.223\server\out\server.js:63138:26)
    at Generator.next (<anonymous>)
    at c:\Users\haegelet\.vscode\extensions\larshp.vscode-abaplint-0.4.223\server\out\server.js:63120:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\haegelet\.vscode\extensions\larshp.vscode-abaplint-0.4.223\server\out\server.js:63116:12)
    at Function.clone (c:\Users\haegelet\.vscode\extensions\larshp.vscode-abaplint-0.4.223\server\out\server.js:63132:16)
    at Handler.<anonymous> (c:\Users\haegelet\.vscode\extensions\larshp.vscode-abaplint-0.4.223\server\out\server.js:9578:59)
(node:12780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[Error - 15:07:27] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
  Code: -32603 
[Error - 15:07:27] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
  Code: -32603 
[Error - 15:07:27] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
  Code: -32603 
[Error - 15:07:27] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Command failed: git clone --quiet --depth 1 https://github.com/abaplint/deps .
  Code: -32603

**Comment by larshp** [comment]
do you have git installed? https://github.com/abaplint/vscode-abaplint/issues/100

**Comment by larshp** [comment]
closing this issue, issue #100 remains to give better error message if git is not installed
