### ISSUE TITLE
View Outline - Follow cursor - Don't working

### ISSUE THREAD

**Issue by norman003** [abaplint/vscode-abaplint#111]
When cursor editor is in block of code don't activate the **form** or **method** in View Outline

**Comment by larshp** [comment]
thanks, does it work for other programming languages in vscode? below is a typescript example, and there is also no activation?

![image](https://user-images.githubusercontent.com/5888506/115239829-6d9d1000-a11f-11eb-8474-8c51810fb720.png)

**Comment by larshp** [comment]
@norman003 ?

**Comment by norman003** [comment]
Thanks, that's easy navigation.
