### ISSUE TITLE
Possibility to customize abaplint config when using abap fs extension

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/vscode-abaplint#113]
Is there a posibility to customize used abaplint's configuration when I connect to system by abap fs extension?

**Comment by larshp** [comment]
"abap fs" = https://marketplace.visualstudio.com/items?itemName=murbani.vscode-abap-remote-fs

currently not, this extension tries to find the `abaplint.json` file, which doesn't exist for abap fs

sometime...

**Comment by Zeatynis** [comment]
Ok, thanks for the reply :)
