### ISSUE TITLE
investigate whether language client needs to trigger for xml

### ISSUE THREAD

**Issue by FreHu** [abaplint/vscode-abaplint#122]
followup to #121  
maybe there is no point to this, but most xml files are not abaplint related
in `extension.ts`
```ts
  const clientOptions: LanguageClientOptions = {
    documentSelector: [{language: "abap"}, {language: "xml"}],
    progressOnInitialization: true,
    initializationOptions:{
      provideFsProxy: true,
    },
    synchronize: {
      fileEvents: workspace.createFileSystemWatcher("**/abaplint.json*"),
    },
  };
```

**Comment by larshp** [comment]
abaplint activates with https://github.com/abaplint/vscode-abaplint/blob/main/package.json#L24

and then subscribe to all abap and XML file changes

like, a dataelement is stored in XML, and valid for securing the abap code is correct

**Comment by FreHu** [comment]
this should stay as it is then
