### ISSUE TITLE
How to edit abaplint config in VSCode

### ISSUE THREAD

**Issue by schmelto** [abaplint/vscode-abaplint#125]
**I want to edit the configs of abaplint in VSCode.**

For example I have following code snipped:

```abap
PARAMETERS: aufnr TYPE acdoca-aufnr,
            bldat TYPE acdoca-bldat.
```
and get following abaplint error:
```
Selection-Screen variable name does not match pattern ^P_.+$: aufnrabaplint(selection_screen_naming)
```
I prefer a variable style pattern without using prefixes as `p_`, `lv_`, etc.

Is there a way to adjust the abaplint settings?

**Comment by larshp** [comment]
run `abaplint -d > abaplint.json` or go to https://playground.abaplint.org to find the default configuration, save the default configuration as "abaplint.json" in the root of your project

or take your starting point in something like https://github.com/abapGit/abapGit/blob/main/abaplint.json

**Comment by schmelto** [comment]
Thanks!
