### ISSUE TITLE
abaplint.json schema: certificate expired error

### ISSUE THREAD

**Issue by larshp** [abaplint/vscode-abaplint#129]
see https://github.com/microsoft/vscode/issues/136787

as a temporary workaround, use https://playground.abaplint.org/ to edit your config

**Comment by FreHu** [comment]
https://github.com/microsoft/vscode/issues/136787#issuecomment-968771447 this also worked for me

**Comment by larshp** [comment]
its a mess, looks like Microsoft has moved the real fix to next months release

**Comment by larshp** [comment]
1.66 which will be released soon looks promising

**Comment by larshp** [comment]
finally, working in vscode 1.66.0

closing
