### ISSUE TITLE
display the local implementations of classes in the vs code abaplint tab

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/vscode-abaplint#142]
display also the local implementations of classes in the vs code abaplint tab:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/102328295/221174040-a513f37e-7a53-4d2e-a228-fba6967a2df4.png">

**Comment by larshp** [comment]
yea, thanks, its a bug

**Comment by larshp** [comment]
close? not sure when this was fixed, but some time ago

![image](https://github.com/abaplint/vscode-abaplint/assets/5888506/b3defec6-2640-4d8d-b887-ed0874433ac3)

**Comment by larshp** [comment]
plus this part moved to https://github.com/abaplint/vscode-abap-artifacts

**Comment by oblomov-dev** [comment]
yes its a while ago, thank you for the fixing this!
