### ISSUE TITLE
find all references: show error if code contains syntax errors

### ISSUE THREAD

**Issue by larshp** [abaplint/vscode-abaplint#153]
as the list will be empty, which is misleading

**Comment by marcellourbani** [comment]
Looking into this now.
I see 3 ways of doing it:

1. checking diagnostics in onReferences when references is empty
2. maintaining a list of files with broken syntax on the server and check that
3. changing core to throw an exception in References.references when syntax is broken (or perhaps even lower, say in lookup or even spaghetti )

Probably going for (1)
