### ISSUE TITLE
F1 masks default key

### ISSUE THREAD

**Issue by marcellourbani** [abaplint/vscode-abaplint#19]
By default F1 opens the command palette, which I use all the time instead of Ctrl+Shift+P
Probably a good idea to use another key by default (I know, it's tough to find a freeish one)

Can alwais override of course

**Comment by larshp** [comment]
yea, I'm planning to use it for language help, like in the ABAP editor

**Comment by larshp** [comment]
override in user settings, will go for ABAP defaults
