### ISSUE TITLE
Add more functionality to "Show abaplint" button

### ISSUE THREAD

**Issue by FreHu** [abaplint/vscode-abaplint#23]
Currently it opens a page with `hello world`.

![image](https://user-images.githubusercontent.com/5097067/63212362-be1ac980-c103-11e9-8c71-bac667e428a6.png)

**Comment by larshp** [comment]
eventually I'd like it to open a "F1 help" like page, https://github.com/abaplint/vscode-abaplint/issues/14 for keywords

and extra information like typing for identifiers
