### ISSUE TITLE
how to handle global defintions goto, eg for "sy"? virtual documents?

### ISSUE THREAD

**Issue by larshp** [abaplint/vscode-abaplint#33]

**Comment by FarukHarmanli** [comment]
Do we have solution here? especially I have this kind of issue, if FM has include. For example FM has some parameters and if this parameters are used in include, abaplint thinks that there is syntax error but in fact there is no syntax error

![1](https://user-images.githubusercontent.com/58327574/70916308-c20c1900-201b-11ea-8aeb-f5b92c62ff4e.jpg)
![2](https://user-images.githubusercontent.com/58327574/70916311-c2a4af80-201b-11ea-8dce-43286edd43db.jpg)

**Comment by larshp** [comment]
@FarukHarmanli thanks, can you open a separate issue for the above?

**Comment by larshp** [comment]
abaplint will no longer return links to documents that does not exist, closing
