### ISSUE TITLE
use eslint instead of tslint

### ISSUE THREAD

**Issue by larshp** [abaplint/vscode-abaplint#46]
tslint is deprecated

**Comment by JohannesKonings** [comment]
documentation of migration TSLint to ESLint: https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

**Comment by larshp** [comment]
some stuff can be taken from https://github.com/abaplint/abaplint, as it is already migrated

**Comment by JohannesKonings** [comment]
Can the ESLint configurations be transferred from abaplint?
If I run `npx tslint-to-eslint-config` as described here https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration it generate some tslint rules within eslint

> ❓ 13 rules are not known by tslint-to-eslint-config to have ESLint equivalents. ❓
  The "@typescript-eslint/tslint/config" section of ./.eslintrc.js configures eslint-plugin-tslint to run them in TSLint within ESLint.
  Check ./tslint-to-eslint-config.log for details.

**Comment by larshp** [comment]
I think just copy the configuration file to this repo

when migrating abaplint, I gave up on using tslint-to-eslint-config, it seemd buggy
