### ISSUE TITLE
Implemented SAP standard interface not found

### ISSUE THREAD

**Issue by JohannesKonings** [abaplint/vscode-abaplint#58]
In this repository I implemented a class with the SAP standard interface IF_HTTP_EXTENSION: https://github.com/JohannesKonings/test-abaplint-interface

In VS Code I got this error messages:
Implemented interface "IF_HTTP_EXTENSION" not found
Method definition "handle_request" in "if_http_extension" not found

![image](https://user-images.githubusercontent.com/14806640/79691314-13911280-825f-11ea-9c2a-b569cf41d4a4.png)

If I check it with the abaplint CLI no issues found:

![image](https://user-images.githubusercontent.com/14806640/79691394-81d5d500-825f-11ea-97c6-3acc8ba2ae5b.png)

Is the VS Code abaplint extension using the repository https://github.com/abaplint/deps? 
Have I to configure something?

Thanks.

**Comment by larshp** [comment]
currently the dependencies are not taken into account, https://github.com/abaplint/vscode-abaplint/issues/27

ie. not cloned, or read locally if it was cloned some other way

**Comment by JohannesKonings** [comment]
is duplicate of #27
