### ISSUE TITLE
Include of FUGR with namespace showing FUGR not allowed

### ISSUE THREAD

**Issue by ed-holland** [abaplint/vscode-abaplint#68]
Not sure if my regex is correct for function groups with namespace.
Error:
![image](https://user-images.githubusercontent.com/53995991/84596067-c941a180-ae5b-11ea-9a18-f9d536b75ba1.png)

Object rule naming:
`        "fugr": "^\/REDWOOD\/",`

**Comment by larshp** [comment]
above screenshot is the "allowed_object_types" rules kicking in, whats the configuration for that rule?

**Comment by ed-holland** [comment]
Yep, was not included there. Many rules ;-)

Thanks
