### ISSUE TITLE
remotefs support

### ISSUE THREAD

**Issue by marcellourbani** [abaplint/vscode-abaplint#69]
I never used abaplint on my own extension because it's just too annoying with the default configuration and there's no way to provide a custom one on an abap server.
It's a real shame not having interoperability in such a small ecosystem.

I was playing with the idea of putting config files in the user profile/workspace and make them look as part of the SAP filesystem.
Would probably have worked for the client, which uses APIs like `vscode.workspace.fs.*`, but it's the language server which loads the config files, and uses `fs.*`, which will never work.

I have a few ideas on how to do this, will write them here to start the discussion:

- have the server asking the config files to the extension
- have the extension passing ifles (or path translations) to the server
- add an API to this extension to allow mine to signal the presence of a config file
- (maybe) support multiple configurations for multiple folders (i.e. abapgit and adt backend might have different defaults for good reasons)

Might also have some minor incompatibility in file formats but I don't think that will be a big deal.

Thoughts?

**Comment by larshp** [comment]
**Configuration**

it should sometime be possible to define a fallback config in the vscode extension configuration, https://github.com/abaplint/vscode-abaplint/issues/54

in https://github.com/abaplint/abaplint-abap-backend its also possible to define a configuration in code inspector, the ABAP part of remote fs could pick it up from there

**File System**
the main trouble is the LSP which does not have a way to read the files initially, see https://github.com/abaplint/vscode-abaplint/issues/21

I would like to avoid calling `fs.*`, probably with the server part asking the client for the full content of the workspace via messaging. This would also be one step towards running this extension only in the browser

**Comment by marcellourbani** [comment]
Ideally the language server should be independent from the extension, so if someone can easily use it from vim/sublime/...

I think a sensible solution for this would be:

* the LS exposes a registerConfigurationProvider function
* the extension calls it if it wants to provide a configuration
  * when registered, the LS tries that first and uses files as a fallback (unless the provider opts out)
* the extension allows to enter the configuration from vscode config system, or to point to another file which then feeds to the LS
* ideally I would have multiple configurations per project, giving each config file a prefix for which is active. Not sure how hard is it to do

**Comment by larshp** [comment]
I would like to do something like the `registerFsProvider`

**Comment by marcellourbani** [comment]
Will have a go  when I feel like.
Afraid will have to convert readConfig to async, and some isReady method on Handler to wait for on initialization. 
Or set the public config in the constructor and make readAndSetConfig public

**Comment by marcellourbani** [comment]
@larshp 
I had a try last week, it kind of works but have to sort a race condition, clean up, test on windows...

The thing I don't like is that we can't expose APIs from the client until the server is initialised, so I had to delay the initialisation and await it to be finished before calling the handler.

Should I go on or you think is too invasive?

PS: I also thought about 2 new features:
1) provide a default abaplint.json from the vscode config when no file is found 
2) allow multiple handlers, like:

```typescript
documents.onDidChangeContent((change) => {
  getHandler(change.document.url).then(h=>h.validateDocument(change.document));
});
```

which would be useful in the plugin where abapgit and eclipse_plugin might have different abaplint.json. I would basically look for the abaplint,json in the roots of the abapgit projects.
Would probably defer this one though as even more invasive, and pointless without the corresponding support from my plugin

**Comment by larshp** [comment]
try opening a pull request, will take a look

**Comment by marcellourbani** [comment]
Will do as soon as I think is good enough to be merged.
Marcello

**Comment by larshp** [comment]
https://github.com/abaplint/vscode-abaplint/pull/74

this is done, closing

**Comment by marcellourbani** [comment]
Sorry to let this hang for so long. Last time I tried was working fine on linux but not on windows (vscode uses /, fs uses \, and abaplint ends up mixing them)
Fought for a bit then dropped. Was still on my radar, but you know...
