### ISSUE TITLE
Question: Create Default Configuration

### ISSUE THREAD

**Issue by habrahams** [abaplint/vscode-abaplint#72]
I am playing around with the abaplint vscode extension, and I am trying to generate a default abaplint.json file.
I assume it would be this command in the command pallet:
![image](https://user-images.githubusercontent.com/16045067/90249997-aa4f9380-de3b-11ea-9120-4ddf3136b8ae.png)
When I run the command nothing happens.

Am I missing something?

How would I go about generating a default abaplint.json file and editing it?

I did see the command abaplint -d > abaplint.json, but I'm not sure if this is docker related or not.

**Comment by larshp** [comment]
thanks, I'll have a look

as a workaround you can install abaplint globally on the PC via `npm install @abaplint/cli -g` it will install the command line interface, and it will then be possible to run `abaplint -d > abaplint.json` on command line

note that the vscode extension bundles abaplint, and it might not always be the latest

**Comment by larshp** [comment]
@g-back do you have time to take a look? #55 

![image](https://user-images.githubusercontent.com/5888506/90251211-a45ab200-de3d-11ea-835c-15bfa1d8a763.png)

**Comment by g-back** [comment]
Same happens when you create a abaplint artifact with the command palette.
Creating the config/artifacts with rightclicking still works though:

![image](https://user-images.githubusercontent.com/27279305/90252823-775bce80-de40-11ea-81af-d769c7e5ce7b.png)

**Comment by larshp** [comment]
hmm, I use that thing a lot, but guess I right click a folder

**Comment by g-back** [comment]
I'll take a look for a fix when I have some spare time

**Comment by larshp** [comment]
@habrahams did the workaround described above work for you? https://github.com/abaplint/vscode-abaplint/issues/72#issuecomment-674057256

**Comment by habrahams** [comment]
@larshp , yes the workaround does work thank you. I also installed the @abaplint/cli thus I was able to generate a default configuration.
