### ISSUE TITLE
Goto definition for # token

### ISSUE THREAD

**Issue by FreHu** [abaplint/vscode-abaplint#93]
In constructor operators like `NEW #( )`, the type is statically known.

**Comment by larshp** [comment]
partially implemented, bug reports welcome

**Comment by larshp** [comment]
@FreHu try again, latest version

```abap
CLASS lcl_bar DEFINITION.
  PUBLIC SECTION.
    METHODS moo.
ENDCLASS.

CLASS lcl_bar IMPLEMENTATION.
  METHOD moo.
    DATA foo TYPE REF TO lcl_bar.
    foo = NEW #( ).
  ENDMETHOD.
ENDCLASS.
```

![image](https://user-images.githubusercontent.com/5888506/142719335-8f954120-0230-445d-bfa6-5c1102aae9c3.png)
